title: "MediLink Contacts"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "https://github.com/AY2324S1-CS2103T-T09-3/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
